# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectiOSTranning1.2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  	
  # Pods for ProjectiOSTranning1.2018
  pod 'SwiftLint'
  target 'ProjectiOSTranning1.2018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectiOSTranning1.2018UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
